import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'zh';

const translations = {
  en: {
    'nav.home': 'Messages',
    'nav.feed': 'Share Wall',
    'nav.profile': 'Me',
    'nav.settings': 'Settings',
    'nav.compose': 'New Post',
    'nav.trending': 'Trending',
    'nav.contacts': 'Contacts',
    'stats.points': 'Reputation',
    'wall.news': 'Social News',
    'wall.friends': 'Friends',
    'wall.mine': 'My Posts',
    'chat.placeholder': 'Message...',
    'chat.hold_to_talk': 'Hold to Talk',
    'chat.release_to_send': 'Release to Send',
    'chat.spark_level': 'Spark Level',
    'chat.transfer': 'Transfer Points',
    'chat.transfer_amount': 'Amount',
    'chat.transfer_confirm': 'Send',
    'chat.dice': 'Dice',
    'chat.rps': 'Rock Paper Scissors',
    'chat.bg': 'Wallpaper',
    'chat.transfer_success': 'Transfer Successful',
    'chat.transfer_received': 'Received',
    'chat.add': 'Add',
    'chat.scan': 'Scan QR',
    'chat.add_contact': 'Add Contact',
    'chat.search_id': 'Search ID',
    'chat.share_card': 'Shared Post',
    'chat.copy': 'Copy',
    'chat.forward': 'Forward',
    'chat.delete': 'Delete',
    'chat.recent': 'Recent Chats',
    'composer.title': 'New Post',
    'composer.placeholder': 'What\'s happening?',
    'composer.post': 'Post',
    'composer.cancel': 'Cancel',
    'composer.analyzing': 'Verifying Safety...',
    'composer.allow_download': 'Allow Download',
    'composer.add_watermark': 'Add Watermark',
    'composer.visibility': 'Visible to',
    'composer.public': 'Public',
    'composer.friends': 'Friends Only',
    'composer.select_topic': 'Select Topic',
    'composer.moderation': 'AI Moderation Enabled',
    'composer.over_limit_cost': 'Extra cost',
    'feed.caught_up': "You're all caught up.",
    'feed.ai_optimized': 'For You',
    'rules.title': 'Point Rules',
    'rules.daily_login': 'Daily Login',
    'rules.post_base': 'Post Base Cost',
    'rules.post_video': 'Post Video Cost',
    'rules.post_overflow': 'Text > 300 chars',
    'rules.interaction_cost': 'Like / Dislike',
    'rules.toxic_penalty': 'Toxic Content Penalty',
    'economy.title': 'Reputation System',
    'settings.title': 'Settings',
    'settings.logout': 'Sign Out',
    'settings.general': 'Preferences',
    'settings.language': 'Language',
    'settings.dark_mode': 'Appearance',
    'settings.clear_cache': 'Clear Media Cache',
    'settings.scan': 'Scan QR',
    'settings.recharge': 'Recharge Points',
    'settings.back': 'Back',
    'login.title': 'Sign in to ZenSpace',
    'login.btn': 'Sign In',
    'browser.leaving': 'Leaving ZenSpace',
    'browser.continue': 'Continue to Site',
    'media.download': 'Save',
    'media.download_denied': 'Save Disabled',
    'media.saved': 'Saved to Photos',
    'media.saved_watermark': 'Saved with watermark by',
    'contacts.title': 'Contacts',
    'contacts.invite': 'Invite',
    'contacts.edit_note': 'Edit Note',
    'contacts.message': 'Message',
    'contacts.requests': 'Friend Requests',
    'contacts.accept': 'Accept',
    'contacts.reject': 'Reject',
    'contacts.all': 'All Contacts',
    'chat.blocked_msg': 'You cannot message this user.',
    'action.follow': 'Follow',
    'action.report': 'Report',
    'action.block': 'Block',
    'action.delete': 'Delete',
    'action.blocked': 'Blocked',
    'action.share': 'Share',
    'action.forward': 'Forward to Chat',
    'action.forward_modal_title': 'Select Chat',
    'settings.displayName': 'Name',
    'settings.bio': 'Bio',
    'settings.verify': 'Verification',
    'settings.verified': 'Verified',
    'settings.unverified': 'Unverified',
    'settings.verify_desc': 'Your identity has been verified.',
    'settings.verify_id': 'Government ID',
    'settings.verify_social': 'Social Link',
    'settings.about_safety': 'About & Safety',
    'settings.privacy': 'Privacy Policy',
    'settings.terms': 'Terms of Service',
    'settings.blocked_users': 'Blocked Users',
    'settings.history': 'Point History',
    'settings.qrcode': 'My QR Code',
    'settings.save': 'Saved',
    'settings.cache_cleared': 'Cache Cleared',
    'settings.news_region': 'News Region',
    'settings.news_desc': 'Customize your social news feed source.',
    'profile.export': 'Export Data',
    'rules.earning': 'Earning Points',
    'rules.post_earn': 'High Quality Post',
    'rules.comment_earn': 'Constructive Comment',
    'rules.spending': 'Spending Points',
    'trending.title': 'Trending',
    'trending.update': 'Updates every 15 min',
    'trending.hot': 'Hot',
    'trending.cat.all': 'All',
    'trending.cat.tech': 'Tech',
    'trending.cat.lifestyle': 'Lifestyle',
    'trending.cat.entertainment': 'Entertainment',
    'trending.cat.finance': 'Finance',
    'login.subtitle': 'A minimalist social platform',
    'login.email': 'Email',
    'login.phone': 'Phone',
    'login.input_email': 'Email address',
    'login.input_phone': 'Phone number',
    'login.input_code': 'Verification Code',
    'login.get_code': 'Get Code',
    'login.or': 'Or continue with',
    'login.agree': 'By signing in, you agree to our Terms of Service and Privacy Policy.',
    'browser.disclaimer': 'You are leaving our secure environment. We are not responsible for external content.',
    'browser.liability': 'User assumes full liability for interactions on external sites.',
    'browser.laws': 'Local laws apply to all external activities.',
    'browser.cancel': 'Go Back',
    'comment.none': 'No comments yet.',
    'comment.placeholder': 'Add a comment...',
    'comment.limit': 'Daily limit reached',
    'pay.title': 'Recharge',
    'pay.select_amount': 'Select Amount',
    'pay.confirm': 'Pay with Apple Pay',
    'pay.processing': 'Processing...',
    'region.Global': 'Global',
    'region.US': 'United States',
    'region.CN': 'China',
    'region.JP': 'Japan',
    'region.UK': 'United Kingdom',
    'region.EU': 'Europe',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
  },
  zh: {
    'nav.home': '消息',
    'nav.feed': '分享墙',
    'nav.profile': '我',
    'nav.settings': '设置',
    'nav.compose': '发帖',
    'nav.trending': '热搜',
    'nav.contacts': '通讯录',
    'stats.points': '积分',
    'wall.news': '社会新闻',
    'wall.friends': '好友动态',
    'wall.mine': '我的动态',
    'chat.placeholder': '发消息...',
    'chat.hold_to_talk': '按住 说话',
    'chat.release_to_send': '松开 发送',
    'chat.spark_level': '火花值',
    'chat.transfer': '转账',
    'chat.transfer_amount': '金额',
    'chat.transfer_confirm': '转账',
    'chat.dice': '掷骰子',
    'chat.rps': '猜拳',
    'chat.bg': '聊天背景',
    'chat.transfer_success': '转账成功',
    'chat.transfer_received': '收到转账',
    'chat.add': '添加',
    'chat.scan': '扫一扫',
    'chat.add_contact': '添加朋友',
    'chat.search_id': '搜索ID/手机号',
    'chat.share_card': '转发内容',
    'chat.copy': '复制',
    'chat.forward': '转发',
    'chat.delete': '删除',
    'chat.recent': '最近聊天',
    'composer.title': '发布',
    'composer.placeholder': '这一刻的想法...',
    'composer.post': '发送',
    'composer.cancel': '取消',
    'composer.analyzing': '安全检测中...',
    'composer.allow_download': '允许下载',
    'composer.add_watermark': '添加水印',
    'composer.visibility': '谁可以看',
    'composer.public': '公开',
    'composer.friends': '仅好友',
    'composer.select_topic': '选择话题',
    'composer.moderation': 'AI 内容审核开启',
    'composer.over_limit_cost': '超长扣分',
    'feed.caught_up': "暂无更多新内容",
    'feed.ai_optimized': '个性化推荐',
    'rules.title': '积分规则',
    'rules.daily_login': '每日登录',
    'rules.post_base': '发帖基础',
    'rules.post_video': '发视频',
    'rules.post_overflow': '超过300字',
    'rules.interaction_cost': '点赞 / 点踩',
    'rules.toxic_penalty': '违规扣分',
    'economy.title': '积分系统',
    'settings.title': '设置',
    'settings.logout': '退出登录',
    'settings.general': '通用',
    'settings.language': '语言',
    'settings.dark_mode': '深色模式',
    'settings.clear_cache': '清理缓存',
    'settings.scan': '扫一扫',
    'settings.recharge': '充值积分',
    'settings.back': '返回',
    'login.title': '登录 阿猫阿狗',
    'login.btn': '登录 / 注册',
    'browser.leaving': '即将离开',
    'browser.continue': '继续访问',
    'media.download': '保存',
    'media.download_denied': '禁止保存',
    'media.saved': '已保存至相册',
    'media.saved_watermark': '已保存，发布者：',
    'contacts.title': '通讯录',
    'contacts.invite': '邀请',
    'contacts.edit_note': '修改备注',
    'contacts.message': '发消息',
    'contacts.requests': '新朋友',
    'contacts.accept': '接受',
    'contacts.reject': '拒绝',
    'contacts.all': '所有朋友',
    'chat.blocked_msg': '无法发送消息',
    'action.follow': '关注',
    'action.report': '举报',
    'action.block': '拉黑',
    'action.delete': '删除',
    'action.blocked': '已拉黑',
    'action.share': '分享',
    'action.forward': '转发给朋友',
    'action.forward_modal_title': '选择聊天',
    'settings.displayName': '名字',
    'settings.bio': '简介',
    'settings.verify': '认证',
    'settings.verified': '已认证',
    'settings.unverified': '未认证',
    'settings.verify_desc': '您的身份已验证',
    'settings.verify_id': '身份证/护照',
    'settings.verify_social': '社交账号',
    'settings.about_safety': '关于与安全',
    'settings.privacy': '隐私政策',
    'settings.terms': '用户协议',
    'settings.blocked_users': '黑名单',
    'settings.history': '积分记录',
    'settings.qrcode': '我的二维码',
    'settings.save': '保存成功',
    'settings.cache_cleared': '缓存已清理',
    'settings.news_region': '新闻地区',
    'settings.news_desc': '定制您的社会新闻来源',
    'profile.export': '导出数据',
    'rules.earning': '获取积分',
    'rules.post_earn': '高质量发帖',
    'rules.comment_earn': '友善评论',
    'rules.spending': '消耗积分',
    'trending.title': '热搜榜',
    'trending.update': '每15分钟更新',
    'trending.hot': '热',
    'trending.cat.all': '综合',
    'trending.cat.tech': '科技',
    'trending.cat.lifestyle': '生活',
    'trending.cat.entertainment': '娱乐',
    'trending.cat.finance': '财经',
    'login.subtitle': '极简社交平台',
    'login.email': '邮箱登录',
    'login.phone': '手机登录',
    'login.input_email': '邮箱地址',
    'login.input_phone': '手机号码',
    'login.input_code': '验证码',
    'login.get_code': '获取验证码',
    'login.or': '其他登录方式',
    'login.agree': '登录即代表您同意用户协议和隐私政策',
    'browser.disclaimer': '您即将离开安全环境，我们不对外部内容负责。',
    'browser.liability': '用户需对外部网站的交互自行承担责任。',
    'browser.laws': '所有行为需符合当地法律法规。',
    'browser.cancel': '返回',
    'comment.none': '暂无评论',
    'comment.placeholder': '写下你的评论...',
    'comment.limit': '今日评论已达上限',
    'pay.title': '充值',
    'pay.select_amount': '选择金额',
    'pay.confirm': '使用 Apple Pay 支付',
    'pay.processing': '处理中...',
    'region.Global': '全球',
    'region.US': '美国',
    'region.CN': '中国',
    'region.JP': '日本',
    'region.UK': '英国',
    'region.EU': '欧洲',
    'theme.light': '浅色',
    'theme.dark': '深色',
    'theme.system': '跟随系统',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations['en']) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: React.PropsWithChildren<{}>) => {
  const [language, setLanguage] = useState<Language>('en');

  // Auto-detect language
  useEffect(() => {
      const browserLang = navigator.language.startsWith('zh') ? 'zh' : 'en';
      setLanguage(browserLang);
  }, []);

  const t = (key: keyof typeof translations['en']) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};